version: '2'

services:
  github-releases-notifier:
    build: ..
    container_name: github-releases-notifier
    restart: always
    environment:
      - GITHUB_TOKEN=<github token>
      - SLACK_HOOK=<slack hook>
      - RELEASES_FILE=/app/releases.json
    command:
      - '-r=golang/go'
      - '-r=justwatchcom/elasticsearch_exporter'
      - '-r=justwatchcom/gopass'
      - '-r=justwatchcom/sql_exporter'
      - '-r=kubernetes/minikube'
      - '-r=prometheus/prometheus'
      - '-r=shurcooL/githubql'

    volumes:
      - ./data:/app/
